language: c
dist: trusty   # Travis build machine is Ubuntu Trusty 14.04 x64
sudo: required # A sudo enabled, full VM is used for building instead of a docker container

branches:
  only:
  - master

addons:
  apt:
    packages:
      - pkg-config
      - make
      - bison
      - g++
      - rpm
      - librpm-dev
      - libpam0g-dev
      - libssl-dev
      - libmysqlclient-dev
      - curl
      - libcurl4-gnutls-dev

script:
  - # Fetch the Build-Powershell-DSC-for-Linux repository for dependencies to build from
  - git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'
  - git clone --recursive 'https://github.com/Microsoft/Build-Powershell-DSC-for-Linux.git' ../bld-dsc
  -
  - # Master branch for all submodules
  - cd ../bld-dsc
  - git submodule foreach git checkout master
  -
  - # Patch in the version of Powershell-DSC-for-Linux that Travis gave to us
  - rm -rf dsc
  - cp -R ../Powershell-DSC-for-Linux dsc
  - cd dsc/build
  - ./configure --noenableulinux
  - make
