language: c
dist: trusty   # Travis build machine is Ubuntu Trusty 14.04 x64
sudo: required # A sudo enabled, full VM is used for building instead of a docker container

git:
  submodules: false

before_install:
  - sudo apt-get update -qq
  # Pre-reqs for building omsagent
  - sudo apt-get install -qq git pkg-config make g++ rpm librpm-dev libpam0g-dev libssl-dev libkrb5-dev curl libcurl4-gnutls-dev  

# We are in /home/travis/build/Microsoft/Powershell-DSC-for-Linux/


install: 
  # Clone OMI
  - cd ..
  - git clone https://github.com/Microsoft/omi.git
  - cd -
  - ln -s ../omi/Unix ./omi-1.0.8

script:
  - cd omi-1.0.8
  - ./configure --enable-debug
  - cd ..
  - ./configure --enable-debug
  - make local 
  - cd omi-1.0.8
  - sudo make install
  - cd ..
  - sudo make reg
  - cd /opt/microsoft/dsc/Scripts/2.6x-2.7x/Scripts/Tests 
  - python ./test_nxProviders.py