language: c
dist: trusty   # Travis build machine is Ubuntu Trusty 14.04 x64
sudo: required # A sudo enabled, full VM is used for building instead of a docker container

branches:
  only:
  - master

addons:
  apt:
    packages:
      - pkg-config
      - make
      - bison
      - g++
      - rpm
      - librpm-dev
      - libpam0g-dev
      - libssl-dev
      - libmysqlclient-dev
      - curl
      - libcurl4-gnutls-dev

script:
  - # Fetch the Build-PowerShell-DSC-for-Linux repository for dependencies to build from
  - git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'
  - git clone --recursive 'https://github.com/Microsoft/Build-PowerShell-DSC-for-Linux.git' ../bld-dsc
  -
  - # Master branch for all submodules
  - cd ../bld-dsc
  - git submodule foreach git checkout master
  -
  - # Patch in the version of PowerShell-DSC-for-Linux that Travis gave to us
  - rm -rf dsc
  - cp -R ../PowerShell-DSC-for-Linux dsc
  - cd ./dsc/build
  - ./configure --noenable-ulinux
  - make local
  - cd ../omi*
  - sudo make install
  - cd ../
  - sudo make reg
#  - sudo cp -r ./Providers/Scripts/2.6x-2.7x/Scripts/Tests /opt/microsoft/dsc/Scripts/2.6x-2.7x/Scripts/
  - sudo ls  ./Providers/Scripts/2.6x-2.7x/Scripts/Tests /opt/microsoft/dsc/Scripts/2.6x-2.7x/Scripts/
#  - cd /opt/microsoft/dsc/Scripts/2.6x-2.7x/Scripts/Tests
#  - sudo python ./test_nxProviders.py
